# Generated by Django 4.0.2 on 2022-02-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='tweet_text',
        ),
    ]
